# Generated by Django 6.1.2 on 2026-10-07 16:27

import apps.tenancy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='favicon',
            field=models.ImageField(blank=True, upload_to=apps.tenancy.models.tenant_brand_path),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, upload_to=apps.tenancy.models.tenant_brand_path),
        ),
    ]
