# Generated by Django 6.1.2 on 2026-10-07 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desk', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprompt',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='approval',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approval',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approval',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='benefitplan',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domainevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='emailauthority',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='emailoutbox',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailoutbox',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='job',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='mailboxconfig',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desk.mailboxconfig'),
        ),
        migrations.AddField(
            model_name='member',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desk.benefitplan'),
        ),
        migrations.AddField(
            model_name='member',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependents', to='desk.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='desk.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='emailauthority',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desk.organization'),
        ),
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='desk.organization'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desk.organizationtype'),
        ),
        migrations.AddField(
            model_name='policy',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desk.organization'),
        ),
        migrations.AddField(
            model_name='policy',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='member',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='desk.policy'),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='desk.policy'),
        ),
        migrations.AddField(
            model_name='emailauthority',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='desk.policy'),
        ),
        migrations.AddField(
            model_name='document',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='desk.policy'),
        ),
        migrations.AddField(
            model_name='benefitplan',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='desk.policy'),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='policy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desk.product'),
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desk.product'),
        ),
        migrations.AddField(
            model_name='project',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='product',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desk.project'),
        ),
        migrations.AddField(
            model_name='referencecounter',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='sla',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='category',
            name='sla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desk.sla'),
        ),
        migrations.AddField(
            model_name='supportgroup',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='category',
            name='support_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='desk.supportgroup'),
        ),
        migrations.AddField(
            model_name='supportgroupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.supportgroup'),
        ),
        migrations.AddField(
            model_name='supportgroupmember',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='supportgroupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportgroup',
            name='members',
            field=models.ManyToManyField(related_name='company_support_groups', through='desk.SupportGroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desk.category'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='desk.organization'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='desk.policy'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desk.project'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='support_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='desk.supportgroup'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='task',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='desk.ticket'),
        ),
        migrations.AddField(
            model_name='notification',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='desk.ticket'),
        ),
        migrations.AddField(
            model_name='emailoutbox',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desk.ticket'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='desk.ticket'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='desk.ticket'),
        ),
        migrations.AddField(
            model_name='approval',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='desk.ticket'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='desk.member'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desk.policy'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='desk.ticket'),
        ),
        migrations.AddField(
            model_name='vectordocument',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desk.knowledgearticle'),
        ),
        migrations.AddField(
            model_name='vectordocument',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='category',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desk.workflow'),
        ),
        migrations.AddIndex(
            model_name='aiprompt',
            index=models.Index(fields=['tenant', 'created_at'], name='aiprompt_t_created'),
        ),
        migrations.AddConstraint(
            model_name='aiprompt',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_aiprompt_tenant_pk'),
        ),
        migrations.AddConstraint(
            model_name='aiprompt',
            constraint=models.UniqueConstraint(fields=('tenant', 'purpose', 'transaction_type'), name='ai_prompt_company_purpose_type'),
        ),
        migrations.AddIndex(
            model_name='aiproviderconfig',
            index=models.Index(fields=['tenant', 'created_at'], name='aiproviderconfig_t_created'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderconfig',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_aiproviderconfig_tenant_pk'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['tenant', 'created_at'], name='auditevent_t_created'),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_auditevent_tenant_pk'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['tenant', 'created_at'], name='domainevent_t_created'),
        ),
        migrations.AddConstraint(
            model_name='domainevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_domainevent_tenant_pk'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['tenant', 'created_at'], name='invitation_t_created'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_invitation_tenant_pk'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['tenant', 'created_at'], name='job_t_created'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_job_tenant_pk'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['tenant', 'created_at'], name='knowledgearticle_t_created'),
        ),
        migrations.AddConstraint(
            model_name='knowledgearticle',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_knowledgearticle_tenant_pk'),
        ),
        migrations.AddIndex(
            model_name='mailboxconfig',
            index=models.Index(fields=['tenant', 'created_at'], name='mailboxconfig_t_created'),
        ),
        migrations.AddConstraint(
            model_name='mailboxconfig',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_mailboxconfig_tenant_pk'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['tenant', 'created_at'], name='notificationtemplate_t_created'),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_notificationtemplate_tenant_pk'),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='notification_template_company'),
        ),
        migrations.AddIndex(
            model_name='organizationtype',
            index=models.Index(fields=['tenant', 'created_at'], name='organizationtype_t_created'),
        ),
        migrations.AddConstraint(
            model_name='organizationtype',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_organizationtype_tenant_pk'),
        ),
        migrations.AddConstraint(
            model_name='organizationtype',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='org_type_company_code'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['tenant', 'created_at'], name='organization_t_created'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_organization_tenant_pk'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='organization_company_code'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['tenant', 'created_at'], name='member_t_created'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_member_tenant_pk'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('tenant', 'policy', 'member_id'), name='member_company_policy_id'),
        ),
        migrations.AddIndex(
            model_name='inboundemail',
            index=models.Index(fields=['tenant', 'created_at'], name='inboundemail_t_created'),
        ),
        migrations.AddConstraint(
            model_name='inboundemail',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_inboundemail_tenant_pk'),
        ),
        migrations.AddConstraint(
            model_name='inboundemail',
            constraint=models.UniqueConstraint(fields=('tenant', 'mailbox', 'message_id'), name='email_company_mailbox_message'),
        ),
        migrations.AddIndex(
            model_name='emailauthority',
            index=models.Index(fields=['tenant', 'created_at'], name='emailauthority_t_created'),
        ),
        migrations.AddConstraint(
            model_name='emailauthority',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_emailauthority_tenant_pk'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'created_at'], name='document_t_created'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_document_tenant_pk'),
        ),
        migrations.AddIndex(
            model_name='benefitplan',
            index=models.Index(fields=['tenant', 'created_at'], name='benefitplan_t_created'),
        ),
        migrations.AddConstraint(
            model_name='benefitplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_benefitplan_tenant_pk'),
        ),
        migrations.AddConstraint(
            model_name='benefitplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'policy', 'code'), name='plan_company_policy_code'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['tenant', 'created_at'], name='policy_t_created'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_policy_tenant_pk'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(fields=('tenant', 'policy_number'), name='policy_company_number'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', 'created_at'], name='project_t_created'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_project_tenant_pk'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='project_company_code'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'created_at'], name='product_t_created'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_product_tenant_pk'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='product_company_code'),
        ),
        migrations.AddIndex(
            model_name='referencecounter',
            index=models.Index(fields=['tenant', 'created_at'], name='referencecounter_t_created'),
        ),
        migrations.AddConstraint(
            model_name='referencecounter',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_referencecounter_tenant_pk'),
        ),
        migrations.AddConstraint(
            model_name='referencecounter',
            constraint=models.UniqueConstraint(fields=('tenant', 'prefix', 'year'), name='reference_company_prefix_year'),
        ),
        migrations.AddIndex(
            model_name='serviceaccount',
            index=models.Index(fields=['tenant', 'created_at'], name='serviceaccount_t_created'),
        ),
        migrations.AddConstraint(
            model_name='serviceaccount',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_serviceaccount_tenant_pk'),
        ),
        migrations.AddIndex(
            model_name='sla',
            index=models.Index(fields=['tenant', 'created_at'], name='sla_t_created'),
        ),
        migrations.AddConstraint(
            model_name='sla',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_sla_tenant_pk'),
        ),
        migrations.AddConstraint(
            model_name='sla',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='sla_company_name'),
        ),
        migrations.AddIndex(
            model_name='supportgroupmember',
            index=models.Index(fields=['tenant', 'created_at'], name='supportgroupmember_t_created'),
        ),
        migrations.AddConstraint(
            model_name='supportgroupmember',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_supportgroupmember_tenant_pk'),
        ),
        migrations.AddConstraint(
            model_name='supportgroupmember',
            constraint=models.UniqueConstraint(fields=('tenant', 'group', 'user'), name='unique_company_group_member'),
        ),
        migrations.AddIndex(
            model_name='supportgroup',
            index=models.Index(fields=['tenant', 'created_at'], name='supportgroup_t_created'),
        ),
        migrations.AddConstraint(
            model_name='supportgroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_supportgroup_tenant_pk'),
        ),
        migrations.AddConstraint(
            model_name='supportgroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='support_group_company_code'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tenant', 'created_at'], name='ticket_t_created'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tenant', 'status'], name='ticket_tenant_status'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_ticket_tenant_pk'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('tenant', 'reference'), name='ticket_company_reference'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'created_at'], name='task_t_created'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_task_tenant_pk'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'created_at'], name='notification_t_created'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_notification_tenant_pk'),
        ),
        migrations.AddIndex(
            model_name='emailoutbox',
            index=models.Index(fields=['tenant', 'created_at'], name='emailoutbox_t_created'),
        ),
        migrations.AddConstraint(
            model_name='emailoutbox',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_emailoutbox_tenant_pk'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['tenant', 'created_at'], name='comment_t_created'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_comment_tenant_pk'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['tenant', 'created_at'], name='attachment_t_created'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_attachment_tenant_pk'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['tenant', 'created_at'], name='approval_t_created'),
        ),
        migrations.AddConstraint(
            model_name='approval',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_approval_tenant_pk'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', 'created_at'], name='transaction_t_created'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_transaction_tenant_pk'),
        ),
        migrations.AddIndex(
            model_name='vectordocument',
            index=models.Index(fields=['tenant', 'created_at'], name='vectordocument_t_created'),
        ),
        migrations.AddConstraint(
            model_name='vectordocument',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_vectordocument_tenant_pk'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['tenant', 'created_at'], name='workflow_t_created'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_workflow_tenant_pk'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='workflow_company_name'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'created_at'], name='category_t_created'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='desk_category_tenant_pk'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'code'), name='category_company_product_code'),
        ),
    ]
