# Generated by Django 6.1.2 on 2026-10-08 10:34

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


# Snapshot these defaults: future prompt/tool edits must not change this migration.
SEED_AGENTS = [
    {
        "code": "CLAIMS",
        "name": "Claims agent",
        "domain": "CLAIMS",
        "system_prompt": "Assist with authorized claim requests. Identify missing information, summarize recorded facts, and draft clear updates. Do not decide coverage or approve settlement.",
        "knowledge_categories": ["Claims"],
        "allowed_tools": [
            "get_claim",
            "get_policy",
            "propose_ticket_comment",
            "search_claims",
            "search_knowledge",
        ],
        "allowed_roles": [],
        "is_default": True,
    },
    {
        "code": "POLICY",
        "name": "Policy agent",
        "domain": "POLICY",
        "system_prompt": "Assist with authorized policies, benefit plans and members. Explain recorded terms and missing information. Do not invent coverage or change enrollment.",
        "knowledge_categories": ["Policy"],
        "allowed_tools": ["get_policy", "search_knowledge", "search_members", "search_policies"],
        "allowed_roles": [],
        "is_default": True,
    },
    {
        "code": "FINANCE",
        "name": "Finance agent",
        "domain": "FINANCE",
        "system_prompt": "Analyze recorded endorsement premium impacts and calculate totals using tools. This application has no payment ledger: never describe premium impacts as payments, refunds issued or settlement balances. State that limitation when asked about payments.",
        "knowledge_categories": ["Finance"],
        "allowed_tools": ["calculate_total", "premium_summary", "search_knowledge"],
        "allowed_roles": ["ADMIN", "MANAGER", "AUDITOR"],
        "is_default": True,
    },
    {
        "code": "TICKETING",
        "name": "Ticketing agent",
        "domain": "TICKETING",
        "system_prompt": "Assist with authorized support tickets. Summarize history, suggest next steps and draft helpful comments. A proposed comment requires the user's review before it is posted.",
        "knowledge_categories": ["Ticketing"],
        "allowed_tools": [
            "get_ticket",
            "propose_ticket_comment",
            "search_knowledge",
            "search_tickets",
        ],
        "allowed_roles": [],
        "is_default": True,
    },
]


def install_agent_guards(apps, schema_editor):
    from apps.tenancy.db_guards import install_guards

    install_guards(
        apps, schema_editor, model_names={"aiagentconfig", "aiagentrun", "aiagentaction"}
    )


def seed_agents(apps, schema_editor):
    Agent = apps.get_model("desk", "AIAgentConfig")
    Tenant = apps.get_model("tenancy", "Tenant")
    for tenant in Tenant.objects.using(schema_editor.connection.alias).all().iterator():
        for defaults in SEED_AGENTS:
            Agent.objects.using(schema_editor.connection.alias).get_or_create(
                tenant_id=tenant.pk,
                code=defaults["code"],
                defaults={k: v for k, v in defaults.items() if k != "code"},
            )


class Migration(migrations.Migration):
    dependencies = [
        ("desk", "0003_tenant_database_guards"),
        ("tenancy", "0003_immutable_company_identity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAgentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=100)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("CLAIMS", "Claims"),
                            ("POLICY", "Policy"),
                            ("FINANCE", "Finance"),
                            ("TICKETING", "Ticketing"),
                        ],
                        max_length=16,
                    ),
                ),
                ("system_prompt", models.TextField(max_length=8000)),
                (
                    "knowledge_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Knowledge categories this agent may search. An empty list disables knowledge retrieval.",
                    ),
                ),
                (
                    "allowed_tools",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A subset of the registered tools for this agent's domain.",
                    ),
                ),
                (
                    "allowed_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional company role restriction. Empty means use existing resource permissions.",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("max_steps", models.PositiveSmallIntegerField(default=4)),
                ("timeout_seconds", models.PositiveSmallIntegerField(default=120)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="desk.aiproviderconfig",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "verbose_name": "AI agent",
                "verbose_name_plural": "AI agents",
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="AIAgentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("support_session_uuid", models.UUIDField(blank=True, editable=False, null=True)),
                ("user_input", models.TextField(max_length=3000)),
                ("access_signature", models.TextField(blank=True)),
                ("resources", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=12,
                    ),
                ),
                ("provider_name", models.CharField(blank=True, max_length=100)),
                ("model_name", models.CharField(blank=True, max_length=160)),
                ("prompt_hash", models.CharField(blank=True, max_length=64)),
                ("answer", models.TextField(blank=True)),
                ("trace", models.JSONField(blank=True, default=list)),
                ("error", models.CharField(blank=True, max_length=200)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="desk.aiagentconfig"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "verbose_name": "AI agent request",
                "verbose_name_plural": "AI agent requests",
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="AIAgentAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(max_length=2000)),
                ("draft_hash", models.CharField(max_length=64)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.tenant"
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="desk.ticket"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="desk.aiagentrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI comment draft",
                "verbose_name_plural": "AI comment drafts",
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="aiagentconfig",
            index=models.Index(fields=["tenant", "created_at"], name="aiagentconfig_t_created"),
        ),
        migrations.AddConstraint(
            model_name="aiagentconfig",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="desk_aiagentconfig_tenant_pk"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiagentconfig",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="agent_company_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiagentconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("tenant", "domain"),
                name="agent_company_default_domain",
            ),
        ),
        migrations.AddIndex(
            model_name="aiagentrun",
            index=models.Index(fields=["tenant", "created_at"], name="aiagentrun_t_created"),
        ),
        migrations.AddConstraint(
            model_name="aiagentrun",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="desk_aiagentrun_tenant_pk"
            ),
        ),
        migrations.AddIndex(
            model_name="aiagentaction",
            index=models.Index(fields=["tenant", "created_at"], name="aiagentaction_t_created"),
        ),
        migrations.AddConstraint(
            model_name="aiagentaction",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="desk_aiagentaction_tenant_pk"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiagentaction",
            constraint=models.UniqueConstraint(
                fields=("run", "draft_hash"), name="agent_run_unique_draft"
            ),
        ),
        migrations.RunPython(install_agent_guards, migrations.RunPython.noop),
        migrations.RunPython(seed_agents, migrations.RunPython.noop),
    ]
